name: Build FAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uFBT
        run: |
          python3 -m pip install ufbt

      - name: Clone Flipper Firmware & Setup App
        run: |
          git clone --depth=1 https://github.com/flipperdevices/flipperzero-firmware firmware
          mkdir -p firmware/applications_user/Flipper-app-1
          cp -r * firmware/applications_user/Flipper-app-1 || true
          cd firmware
          ufbt faps

      - name: Build app
        run: |
          cd firmware
          ufbt faps

      - name: Upload FAP
        uses: actions/upload-artifact@v4
        with:
          name: flipper-app
          path: firmware/dist/**/*.fap
